services:
  academic-service:
    build: .
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3306/academic_service
      PLAYWRIGHT_BROWSERS_PATH: /opt/pw-browsers
    volumes:
      - /var/www/student-service-images:/var/www/student-service-images
      - /opt/pw-browsers:/opt/pw-browsers
    restart: unless-stopped
