package com.example.academic_service.entity;

public enum Submodule {
    // Setup
    SYSTEM_SETTINGS, ACADEMIC_YEARS, SHIFTS, CLASSES, GROUPS, SECTIONS, GRADING_POLICIES,
    ACADEMIC_CALENDAR, CLASS_ROUTINE,
    // Students
    STUDENTS, STUDENT_ARCHIVE, STUDENT_TRANSFER,
    // Exam
    EXAM_ROOMS, EXAM_SUBJECTS, EXAM_TYPES, EXAM_ROUTINES,
    // Marking
    EXAM_COMPONENTS, MARKING_STRUCTURES, MARK_ENTRY,
    // Results
    SESSION_RESULTS, ROUTINE_RESULTS, ANNUAL_RESULTS, MERIT_LIST, RESULT_STATISTICS,
    // Downloads
    STUDENT_ID_CARD, ADMIT_CARD, PROGRESS_REPORT, SEAT_PLAN,
    // HR
    HR_STAFF, HR_DESIGNATIONS, HR_LEAVE_TYPES, HR_LEAVE_REQUESTS, HR_LEAVE_POLICIES,
    // User Management
    ACCESS_ROLES, SYSTEM_USERS,
    // Administration
    ADMIN_MANAGEMENT
}
